### ISSUE TITLE
[10 beta] NON_CREATED shortcut doesn't exist

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#15]
As read in the [wiki](https://github.com/Utodev/ngPAWS/wiki/The%20start%20database#user-content-the-objects-section-obj), there is a special location called *NON_CREATED*. But this shortcut doesn't exist and compiler gives an error.

The easiest workaround is to define it:
`#define const NON_CREATED = 252`

Also, should it be called NO**T**_CREATED?

**Comment by Utodev** [comment]
It's amazing to see how such a simple feature fail has been unnoticed for more than ten years (as this bug is also in Superglus  and Paguaglus, ngPAWS acestors). I have fixed it and will be avaliable in next release. Your temporary patch is OK and compatible with my fix, so you can use it in the meantime.

You are also right that it should be NOT_CREATED, but as for many years it has been described in documentation as NON_CREATED, I've decide tu support both NON and NOT shortcuts.

**Comment by cibersheep** [comment]
Hehehe I guess because it's easy to workaround.
I agree with you i keeping the name as in the documentation.

**Comment by Utodev** [comment]
The fact I don't use them myself, otherwise they'd been located long ago, but for me is easier and shorter using 254, 253, 252 :-). Less readable though, but those numbers are engraved in stone in my mind since the old PAWS days.
