### ISSUE TITLE
[10beta] locno for images must be in numbers

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#17]
Having this definitions in code.txp
```
 #define loc lFrontera 3
 #define pic loc03.png lFrontera
```
when adventure is compiled, image for lFrontera is empty (I think the second line is _translated_ as ` #define pic loc03.png 0`). Forcing to write the code as `#define pic loc03.png 3` making adaptation or utter edition a bit more complicated.

**Comment by Utodev** [comment]
As far as I know, txtpass is not a double-pass preprocessor so that is not possible, though I agree it's inconvenient.
Anyway albeit txtpaws is used in ngpaws, it's an external application with its own github page. Open this issue in its project page, maybe you're luckier :-)

**Comment by cibersheep** [comment]
¡Es cierto!
¿Te puedes creer que **ahora** me acabo de encontrar la wiki del txtpaws... ¡ay, ay ay!

A workaround might be defining the name and image in the `/LTX` area as read in [txtpaws wiki](https://github.com/Baltasarq/txtpaws/wiki):
```
/LTX
/1 = lFrontera(loc03.png)
```
For me, is clearer all in definitions area but at least we have a way of doing it.

**Comment by Baltasarq** [comment]
Txtpaws was not designed for that. It is a multi-pass preprocesador,
created for while ngPaws did not have its own capabilities for variables,
though it has survived up until now, because of ngPaws' programner laziness
;-)

-- baltasarq

El dom., 19 mar. 2017 11:59, Joan CiberSheep <notifications@github.com>
escribió:

¡Es cierto!
¿Te puedes creer que *ahora* me acabo de encontrar la wiki del txtpaws...
¡ay, ay ay!

A workaround might be defining the name and image in the /LTX area as read
in txtpaws wiki <https://github.com/Baltasarq/txtpaws/wiki>:

/LTX
/1 = lFrontera(loc03.png)

For me, is clearer all in definitions area but at least we have a way of
doing it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Utodev/ngPAWS/issues/17#issuecomment-287608631>, or mute
the thread

**Comment by Baltasarq** [comment]
My decission, published in the issues section of the txtPAWS github page:
> Note that txtPAWS was originally conceived as a simple preprocessor a la cpp, but grew to manage multimedia assets and many more characteristics (probably due to my own enthusiastic attitude, my fault).
These puts a lot of weight off the shoulders of Superglus/ngPAWS and the like programmers, but looking to the past it was an error: txtPAWS should have existed meanwhile labels and multimedia assets management were not added to Superglus/ngPAWS. In general, preprocessors are auxiliary tools, not vital parts.

> So, yes to to bugfixes, no to new features, and certainly no to look for labels in substituted content, which could potentially break execution. As you noted, there are other approaches that serve the objective you were pursuing.
