### ISSUE TITLE
PICTURE resno ignores grf numbers

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#19]
If project is set up as:
```
#define grf enanomalauva.png 200
_ _
 PICTURE 200
```

No image will be sown

**Comment by Utodev** [comment]
To avoid colission between pic and grf definitions, both defining an image/picture, txtpaws adds 256 (by default) to every "#define grf", so your 200 actually becomes resource number 456. You can change the value added by calling txtpaws with MAXNUMLOCS parameter. If you really need to call a picture by number after making a definition (I assume you have a good reason for noy using "PICTURE enanomaluva.png" instead of "PICTURE 200") you will have to add 256 too.

This is somehow related with  ngPAWS ancestor Superglus, and the Blorb specification required for Glulx packages, but that is a long story :-)

**Comment by cibersheep** [comment]
Nice!
Thanks again for taking the time to explain all the bits and pieces.
Let's try to remember that long story for when you have more time off.
