### ISSUE TITLE
[Wishlist] Add "How to save/load game" in HELP section

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#20]
I have talked to some new IF gamers and one nice thing would be add how to save/load the game in the help text.

**Comment by Utodev** [comment]
Do you mean the help text that appears when you type "HELP" when playing?

**Comment by 8bat** [comment]
How about making HELP a rule in the "start" database, instead of a special condact?  So developers are encouraged to modify it to suit their game.

Or if you don't mind engaging in a little light heresy, could we make an on-screen cog menu that shows a clickable list of saved games?  In fact, such a menu would be a good place to link to other things newbies don't know to ask for, like the "HELP" command itself :)

I've [experimented with menus already](https://8bat.github.io/vbca/play/) - hover the mouse over the ">" on the left of the text prompt to see information and common actions.  I'm not all that happy with it aesthetically, but mechanically it would be easy enough to convert to a cog menu.

**Comment by cibersheep** [comment]
@Utodev Yep. One of the things a player (that never played if) asked me is «How do I save» and pointed me that it is not in the default help text.

**Comment by Utodev** [comment]
I have just pushed a change to helpl condact. A quite simple change as I don't have too much time to make better improvements right now.

I have also fixed a bug with compiler but I'm waiting for reporter confirmation to proceed with a new release.

I think it would be nice to have a load menu, but I'm afraid it would be a bit complicated to make a proper one that adapts to all devices without crossing the line I don't want to cross, the one that lets the developer decide which CSS he/she is using.
