### ISSUE TITLE
[Whishlist] List of saved games

### ISSUE THREAD

**Issue by cibersheep** [Utodev/ngPAWS#21]
Ok. This is more a reminder. First I want to properly finish an adventure, then a translation for ngPAWS and then let's check if it's possible to do a _condact_ to print the saved games in the browser.

**Comment by cibersheep** [comment]
Mmm... it doesn't seem difficult to implement but I don't know how to fit in the project.
It could be something like:

```
for(var i in localStorage) {
  k = i.slice(16);
  if (k) {
    // Print k;
  }
}
```

**Comment by Utodev** [comment]
You are in the good way. I'd rather use substring() instead of slice and would also check first 16 characters are actually "ngpaws_savegame_" to avoid getting some other variable long enough.

for(var savedgames in localStorage) {
  gamePrefix = savedgames.substring(1,16);   // takes out ngpaws_savegame_
 if (gamePrefix == 'ngpaws_savegame_')
{
gameName = savedgames.substring(16);
writelnText(text);
 }
}
}

Note: this is untested code, I use to forgot how substring() parameters work and I have not checked them.

About how does it fit in the project, clearly as a plugin condact:

https://github.com/Utodev/ngPAWS/wiki/Creating-your-own-condacts

I'd save a "LISTSAVEGAMES" condact would do it.

**Comment by cibersheep** [comment]
Excellent. I like that very clean `if (gamePrefix == 'ngpaws_savegame_')`
I have tried (also in the console) and this works :P
```
for(var savedgames in localStorage) {
  gamePrefix = savedgames.substr(0,16); 
  if (gamePrefix == 'ngpaws_savegame_') {
    gameName = savedgames.substring(16);
    writelnText(gameName);
  }
}

THANKS!
```

**Comment by cibersheep** [comment]
Done! I have added the new condact to the pull request (I thought they would not be joint together).
Thanks for the help

**Comment by cibersheep** [comment]
Ahora sí que creo que he hecho el [Pull Request](https://github.com/Utodev/ngPAWS/pull/23) como toca :D
